version: '2'
services:
  'mongodb':
    image: mongo:latest
    ports:
        - 27017:27017
    volumes:
        - ./target/mongo:/data/db
    environment:
        ## Development only!
        - MONGODB_USERNAME=user
        - MONGODB_PASSWORD=pass
        - MONGODB_DATABASE=test
  'rabbitmq':
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
  'mariadb':
    image: mariadb
    ports:
        - "3306:3306"
    environment:
        ## Development only!
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=contessa
  'minio':
    image: minio/minio
    ports:
        - "9000:9000"
    volumes:
        - "./target/minio:/contessa"
    environment:
        ## Development only!
        - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
        - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    command: server /contessa
  'cassandra':
    image: cassandra
    ports:
        - "9042:9042"   # Native transport
        - "7199:7199"   # JMX
        - "9160:9160"   # Thrift clients
    volumes:
        - ./target/cassandra:/var/lib/cassandra
    environment:
        - "CASSANDRA_CLUSTER_NAME=contessa"
