### ---------------------------------------------
### Default Contessa configuration properties.
### ---------------------------------------------
contessa:
  storage:
    ### -----------------------------------------
    ### The storage type to use. Supports a small
    ### set of types:
    ###
    ### `SQL`   - (default) storing assets into
    ###           an SQL database.
    ###
    ### `NOSQL` - storing assets into a NoSQL
    ###           database.
    ###
    ### `LOCAL` - file based storage type, saving
    ###           content assets to a local file
    ###           system.
    ###
    ### `NONE`  - disables the storage; used only
    ###           for testing and development.
    ### -----------------------------------------
    type: SQL
  ui:
    ### -----------------------------------------
    ### Enables the REST-ful interface, allowing
    ### simple HTTP upload and download of
    ### assets.
    ### -----------------------------------------
    #rest.enabled: true
    ### -----------------------------------------
    ### Enables the RabbitMQ interface, providing
    ### query/response based access to assets.
    ### -----------------------------------------
    #amqp.enabled: true
    ### -----------------------------------------
    ### Enables file based, drop-folder, access
    ### to assets.
    ### -----------------------------------------
    #file.enabled: true
### ---------------------------------------------
### Customized configuration properties for the
### Contessa application.
### ---------------------------------------------
spring:
  application:
    name: contessa
  jpa:
    hibernate:
      ddl-auto: create
### ---------------------------------------------
### Enables full management features, best used during
### development, in order to view and audit anything
### in the runtime application context.
### ---------------------------------------------
management:
  context-path: /management
  security.enabled: false
  health:
    ## None of the health-endpoints works by default, since we are
    ## custom enabling/disabling the modules.
    #rabbit.enabled: false
    #mongo.enabled: false
#endpoints:
#  auditevents.enabled: true
#  autoconfig.enabled: true
#  configprops.enabled: true
#  docs.enabled: true
#  dump.enabled: true
#  env.enabled: true
#  health.enabled: true
#  heapdump.enabled: true
#  info.enabled: true
#  logfile.enabled: true
#  loggers.enabled: true
#  mappings.enabled: true
#  metrics.enabled: true
#  shutdown.enabled: true
#  trace.enabled: true
logging:
  level:
    #root: ERROR
    com.studiomediatech.contessa: DEBUG
